"use strict";

export default {
    "arrow-body-style": ["error", "as-needed", { "requireReturnForObjectLiteral": false }],
    "arrow-parens": ["error", "as-needed", { "requireForBlockBody": false }],
    "arrow-spacing": ["error", { "before": true, "after": true }],
    "constructor-super": "error",
    "generator-star-spacing": ["error", { "before": true, "after": false, anonymous: "after", method: "before" }],
    "no-class-assign": "error",
    "no-confusing-arrow": ["error", { "allowParens": true }],
    "no-const-assign": "error",
    "no-dupe-class-members": "error",
    "no-duplicate-imports": ["error", { "includeExports": true }],
    "no-new-symbol": "error",
    "no-this-before-super": "error",
    "no-useless-computed-key": ["error", { "enforceForClassMembers": true }],
    "no-useless-constructor": "error",
    "no-useless-rename": ["error", { "ignoreDestructuring": false, "ignoreImport": false, "ignoreExport": false }],
    "no-var": "error",
    "object-shorthand": ["error", "always"],
    "prefer-arrow-callback": ["error", { "allowUnboundThis": false }],
    "prefer-const": "error",
    "prefer-destructuring": ["error", { "array": true, "object": true }, { "enforceForRenamedProperties": true }],
    "prefer-numeric-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "require-yield": "error",
    "require-yield": "error",
    "rest-spread-spacing": ["error", "never"],
    "sort-imports": ["error", { "ignoreCase": false, "ignoreDeclarationSort": false, "ignoreMemberSort": false, "memberSyntaxSortOrder": ["none", "all", "single", "multiple"] }],
    "symbol-description": "error",
    "template-curly-spacing": "error",
    "yield-star-spacing": ["error", "after"],
};
