"use strict";

export default {
    "no-console": "off",
    "for-direction": "error",
    "getter-return": ["error", { allowImplicit: true }],
    "no-async-promise-executor": "error",
    "no-await-in-loop": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": ["error", "always"],
    "no-constant-condition": ["error", { "checkLoops": true }],
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-dupe-args": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": ["error", { "allowEmptyCatch": false }],
    "no-empty-character-class": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-extra-parens": ["error", "all", { "conditionalAssign": false, "returnAssign": false, "ignoreJSX": "multi-line", "enforceForArrowConditionals": false, "enforceForSequenceExpressions": false, "enforceForNewInMemberExpressions": false }],
    "no-extra-semi": "error",
    "no-func-assign": "error",
    "no-import-assign": "error",
    "no-inner-declarations": ["error", "both"],
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": ["error", { "skipStrings": false, "skipComments": false, "skipRegExps": false, "skipTemplates": false }],
    "no-misleading-character-class": "error",
    "no-obj-calls": "error",
    "no-prototype-builtins": "error",
    "no-regex-spaces": "error",
    "no-setter-return": "error",
    "no-sparse-arrays": "error",
    "no-template-curly-in-string": "error",
    "no-unexpected-multiline": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": ["error", { "enforceForOrderingRelations": true }],
    "require-atomic-updates": "error",
    "use-isnan": ["error", { "enforceForSwitchCase": true, "enforceForIndexOf": true }],
    "valid-typeof": ["error", { "requireStringLiterals": true }]
};
