version: "3"

services:
    npm:
        image: node
        user: node
        entrypoint: npm
        working_dir: /home/node
        volumes:
            - .:/home/node

    shell:
        image: node
        user: node
        working_dir: /home/node
        volumes:
            - .:/home/node
